export const INGREDIENTS_DATA = "INGREDIENTS_DATA";
export const SET_INGREDIENTS_DATA = "SET_INGREDIENTS_DATA";
export const INGREDIENTS_SELECTED = "INGREDIENTS_SELECTED";
export const ADD_IN_INGREDIENTS_SELECTED = "ADD_IN_INGREDIENTS_SELECTED";
export const REMOVE_ONE_INGREDIENTS_SELECTED = "REMOVE_ONE_INGREDIENTS_SELECTED";
export const INGREDIENT_INFO = "INGREDIENT_INFO";
export const ORDER_LIST = "ORDER_LIST";
